spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_practise
    username: root
    password: 9780619
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /res/** #修改静态资源访问路径
#    web:
#      resources:
#        static-locations:
#          - classpath:/sgstatic/
#          - classpath:/static/ #修改静态资源访问路径

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换

logging:
  level:
    com.wzres.mapper: debug #开启日志

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
#  type-aliases-package: com.wzres.domain   # 配置哪个包下的类有默认的别名
